### ISSUE TITLE
Create bridge labelled provisioned ipv4 task failing

### ISSUE THREAD

**Issue by smalleni** [openshift-kni/baremetal-deploy#270]
The task at https://github.com/openshift-kni/baremetal-deploy/blob/master/ansible-ipi-install/roles/node-prep/tasks/40_bridge.yml#L31 fails with
https://gist.githubusercontent.com/smalleni/87b85983922dbad17ea9dad984d7951c/raw/d71fe7d367cd4225489cfda4c9a92ec6c747ce9c/gistfile1.txt

However, sometimes rerunning the task works. Manually running the nmcli module at https://github.com/openshift-kni/baremetal-deploy/blob/master/ansible-ipi-install/roles/node-prep/library/nmcli.py with the module arguments generated by the task, the correct command seems to be executing

['/usr/bin/nmcli', 'con', 'add', 'type', 'bridge', 'con-name', 'provisioning', 'ifname', 'provisioning', 'ipv4.addresses', '172.22.0.1/24', 'ipv4.method', 'manual', 'autoconnect', 'yes', 'bridge.ageing-time', '300', 'bridge.forward-delay', '15', 'bridge.hello-time', '2', 'bridge.max-age', '20', 'bridge.priority', '128', 'bridge.stp', 'no']

*Sometimes* rerunning the task works.

**Comment by smalleni** [comment]
@rlopez133 @dustinblack FYI

**Comment by smalleni** [comment]
From what we have debugged so far along with @dustinblack, looks like a problem with our fork. We have another role that is called before the node-prep role in playbook.yml and it's using an outdated version of nmcli.py module. However the mystery remains as to why the node-prep role is also using the nmcli module from the previous role and not what is in its on library subdirectory.

**Comment by rlopez133** [comment]
@smalleni - I've seen similar issues in the past with regards to library files and how the playbook.yml reads them. My guess is Ansible sees that you already have the nmcli.py in a role and uses the first one it loads throughout the playbook since it has the same name. 

A couple things you can try -- change your nmcli.py in your other role to the updated version
If you create a library directory at the same level as your playbook.yml and place the updated nmcli.py that will take precedence over any nmcli.py within your roles.

**Comment by smalleni** [comment]
@rlopez133 Ack thanks, I think ansible needs to be fixed though. I created a simple reproducer and opened this issue https://github.com/ansible/ansible/issues/68694

**Comment by rlopez133** [comment]
@smalleni OK for me to close this as it's related to ansible itself not the playbook?

**Comment by smalleni** [comment]
Sure @rlopez133 go for it.
