### ISSUE TITLE
Move information about cleaning up from a previous deploy to its own section

### ISSUE THREAD

**Issue by larsks** [openshift-kni/baremetal-deploy#417]
The information on how to clean up after a previous deploy is hidden in the section 7.1 ("Configuring the install-config.yaml file"). This should be moved to its own top-level section so that is easy to find when looking through the table of contents, and expanded to include the fact that the operator must be delete the `clusterconfigs` directory in order to prevent Terraform from failing.

**Comment by rlopez133** [comment]
Good idea! We can easily make that modification.

**Comment by iranzo** [comment]
@larsks can you check https://deploy-preview-419--baremetal-deploy.netlify.app/4.4/deployment#cleaning-up-previous_ipi-install-prerequisites (PR 419) to see if it covers completely the request?

Thx!

**Comment by rlopez133** [comment]
@iranzo I would say this shouldn't be a 7.1 due to flow, but instead in chapter 11 as a subsection. 

My thinking here is want user to go through all their checklist all the regular flow and just before they are going to deploy give them this optional section in case they somehow attempted deploying prior to reading this doc or were reattempting.

**Comment by iranzo** [comment]
ok, let me move it

**Comment by larsks** [comment]
That looks good to me. Thanks!
