### ISSUE TITLE
network setup for the IPI deployment

### ISSUE THREAD

**Issue by crissonpl** [openshift-kni/baremetal-deploy#427]
Hi,

I'm following the doc trying to deploy the OCP with IPI and I have a few questions. I'm using bare metal servers from a cloud provider and they have some preconfigured settings.

1. the provisioning and baremetal network - is there any workaround so they can be in the same physical VLAN as in the doc it's written it must be on different ones. is it because of the dhcp?
2. in my servers I have 4 interafces but for the install I can use only eno1 and eno3 (eno2 and eno4 are disabled) so it's 1st and 3rd. will it work? eno1 is for the provisioning network and eno3 for baremetal.
3. should the bootstrap node have a reservation in dhcp in the baremetal network? it's not mentioned how it will get an IP on the baremetal network
4. the provisioning node - it's baremetal IP - is it set with this command - nmcli connection modify provisioning ipv4.addresses 172.22.0.1/24 ipv4.method manual - is it correct?
5. where is the definition of the IPs in the provisioning network for the cluster nodes including bootstrap? I believe there is an issue to address this requirement

Thanks

**Comment by rlopez133** [comment]
Hi @crissonpl ,

Glad to hear you are following the doc! To answer your questions

1. The IPI on BM installer creates a bootstrap VM which then runs its own DHCP dnsmasq that serves the Provisioning Network. The provisioning network is what is used to provision the OpenShift nodes. In a nutshell, yes, they must be different. 

2. Yes no issue with that. Just make sure this is consistent throughout your OCP nodes. 

3. It doesn't need a DHCP reservation on the baremetal network. Essentially what it does it attempts to get an available IP address from the external DHCP. Mind you the bootstrap VM has a short shelf-life, once the OpenShift nodes are installed, the bootstrap VM deletes itself once its completed its duties

4. The 172.22.0.1 address is referring to the provisioning network not the baremetal network. Example of this on step 11: https://openshift-kni.github.io/baremetal-deploy/4.4/Deployment.html#preparing-the-provisioner-node-for-openshift-install_ipi-install-prerequisites

5. The provisioning network is a network that is used to provision the RHCOS images on the OpenShift cluster nodes. It is a non-routable network. It is expected that your OpenShift cluster nodes PXE off this provision network which is all done by the bootstrap VM. 

FYI: There is an Ansible playbook that automates the install process as well found here: https://openshift-kni.github.io/baremetal-deploy/4.5/Ansible%20Playbook%20Install . I think this would be a great test after you've gone through the manual process to understanding how the underlying process works.

If you have any more Qs, feel free to post here.

**Comment by crissonpl** [comment]
Hi @rlopez133 

thanks for such an extensive info. As I mentioned my bare metals are preconfigured and it seems to be hard to get those two interfaces to be configured on a different VLANs.

I understand that the external DHCP server beside the pool of fixed IP-MAC needs to have at least one free IP for the bootrsap which it will require via the bridge. And than it starts it's own DHCP on the provisioning network.

The provisioning node can be configured statically with both IPs correct?

What if I do a static reservation for the boostrap node on the external DHCP? I guess I could configure it to have a given MAC and than make the binding. Will than it work on the same VLAN?

**Comment by rlopez133** [comment]
> Hi @rlopez133
> 
> thanks for such an extensive info. As I mentioned my bare metals are preconfigured and it seems to be hard to get those two interfaces to be configured on a different VLANs.
> 
This is likely going to stop you from deploying. They need to be isolated from each other (provisioning net and baremetal net)

> I understand that the external DHCP server beside the pool of fixed IP-MAC needs to have at least one free IP for the bootrsap which it will require via the bridge. And than it starts it's own DHCP on the provisioning network.

Correct. 

> 
> The provisioning node can be configured statically with both IPs correct?

The provisioning IP needs to be configured statically, i.e. provisioning bridge could be assigned 172.22.0.1 as its address. 

If say you decide you want this to be something different you may need to change and add into your install-config.yaml things like. However, personally I always use the 172.22.0.1 so I don't need to do the below. Also since the provisioning network has a short shelf life (just deploying OCP cluster nodes) unless you had some conflict with this range, I don't see why you wouldn't use it. 

```
platform:
  baremetal:
    bootstrapProvisioningIP: "172.22.0.2"
    clusterProvisioningIP: "172.22.0.3"
    provisioningDHCPRange: "172.22.0.10,172.22.0.100"
    
  ```
bootstrapProvisioningIP - The IP on the bootstrap VM where the provisioning services run while the control plane is being deployed.
  clusterProvisioningIP - The IP within the cluster where the provisioning services run.

We are in the process of adding these parameters and a few more inside the documentation. It's an active WIP. 


> 
> What if I do a static reservation for the boostrap node on the external DHCP? I guess I could configure it to have a given MAC and than make the binding. Will than it work on the same VLAN?

I guess as long as you can make sure the bootstrap VM comes up with the given MAC address that could work. From the perspective of the installer, it doesn't have any power over the external DHCP it just assumes you can give out DHCP addresses out and the bootstrap VM is just going to try and pick one up.

**Comment by rlopez133** [comment]
Hey @crissonpl , closing. Feel free to reopen if needed.
