### ISSUE TITLE
Firmware and chassis inspection increases deployment time > 10 minutes

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/baremetal-deploy#507]
It seems the latest changes to inspect if using redfish/ipmi makes the playbook slower:

```
node-prep : Get all the firmware results from all the hosts ----------- 585.74s
node-prep : Get all the chassis results from all the hosts ------------- 91.85s
```

Can this be disabled somehow? I guess it is related to https://github.com/openshift-kni/baremetal-deploy/issues/497 but just in case.

Thanks.

**Comment by iranzo** [comment]
#497 was  because of some issues that were found in some flaky bios that were reporting redfish support but then was failing to operate properly, but is still under discussion

**Comment by rlopez133** [comment]
Indeed it would make the playbook slower because it needs to gather information from the systems. This is required because we want to be able to intelligently decide if a customer should use IPMI or RedFish on their environments. I personally don't see a 10 or 15 min extra to a full install a deal breaker here.

**Comment by e-minguez** [comment]
I agree it is a good feature, but I guess that if you know what you need/want, you can just specify it somehow? Like an ansible variable where you specify either ipmi or redfish.

**Comment by rlopez133** [comment]
The issue is RedFish requires very specific critieria (e.g. firmware versions) so just saying you want RedFish via a variable is not good enough. Likely customer will attempt RedFish and just fail. With this method, I can actually determine if RedFish will work or not and set it for them without ever asking.

**Comment by e-minguez** [comment]
I'm not saying to disable it, but giving the _advanced user_ the ability to choose would be nice :+1:

**Comment by rlopez133** [comment]
@ptrnull @e-minguez Due to the complexity of making this work, what I believe the plan is going to be is add a variable that lets you disable checking if redfish can be used. However, if disabled it will just default to IPMI (previous default behavior). There is already so much logic involved in creating the install-config.yaml file that I want to start limiting that.

**Comment by rlopez133** [comment]
@ptrnull @e-minguez - Can you test this PR and ensure it works as expected? https://github.com/openshift-kni/baremetal-deploy/pull/511 If you now set enable_hw_detection=false in the inventory hosts file with this PR it will make everything use IPMI.
